version: '3.8'

services:
  web:
    build: .
    #ports:
     - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./static:/app/static
    restart: unless-stopped
    networks:
      - app-network  # Attach to the same network as the reverse proxy

networks:
  app-network:
    external: true  # Use the existing network from Nginx Proxy Manager